### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by jojogamerCt** [princeton-nlp/SWE-agent#75] opened 2024-04-05 15:06 UTC
I read a fix is under the way, but I though it would be a great idea showing the developers the error anyways.

![image](https://github.com/princeton-nlp/SWE-agent/assets/51884596/7061669a-e5de-4eab-9a11-83b4cf41ede3)

Is there an exstimated time on when it should be fixed?

**Comment by Delfigore** [comment] 2024-04-05 15:11
Getting the same error(

**Comment by Delfigore** [comment] 2024-04-05 15:12
The SIGALRM signal is a Unix-specific signal that is not available on Windows

**Comment by klieret** [comment] 2024-04-05 15:54
This is a duplicate of #40

**Closed by klieret** 2024-04-05 15:54 UTC
Labels: duplicate

**Comment by klieret** [comment] 2024-04-06 16:51
You can now use the docker setup to run swe-agent on Windows, see readme
