### ISSUE TITLE
Run on a local directory (instead of GitHub issue)

### ISSUE THREAD

**Issue by agamm** [princeton-nlp/SWE-agent#63] opened 2024-04-05 01:35 UTC
It would be great if it could run on a local directory and suggest a new git branch so I could compare the changes + request a change without needing github and a repo.

PS. Right now I don't know how to actually make changes from `run.py` it outputted some terminal logs but I can't reasonably use them for anything.

**Comment by klieret** [comment] 2024-04-05 02:17
Thanks for the suggestion, but duplicate of #57 and #43.

**Closed by klieret** 2024-04-05 02:17 UTC
