### ISSUE TITLE
Traceback & Multiple errors

### ISSUE THREAD

**Issue by borthdor** [princeton-nlp/SWE-agent#54] opened 2024-04-04 19:18 UTC
i always get these errors what should i do?
![image](https://github.com/princeton-nlp/SWE-agent/assets/59848934/388b25c2-af59-4429-8617-2bb20fbd1992)

**Comment by klieret** [comment] 2024-04-04 19:22
This is a duplicate of #40. There are issues running under Windows at the moment.

**Closed by klieret** 2024-04-04 19:22 UTC
