### ISSUE TITLE
[small feature req] Output list of all available models if user requests a model that doesn't exist

### ISSUE THREAD

**Issue by ofirpress** [princeton-nlp/SWE-agent#295] opened 2024-05-02 04:53 UTC
### Describe the feature

That's it.

### Potential Solutions

Thank you

**Comment by klieret** [comment] 2024-05-02 14:17
Good idea!

**Comment by klieret** [comment] 2024-10-23 17:25
Closing as duplicate of #224 . has the same problems.

**Closed by klieret** 2024-10-23 17:25 UTC
Labels: ✨ enhancement
