### ISSUE TITLE
Error when running run.py script: AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by Audyari** [princeton-nlp/SWE-agent#145] opened 2024-04-09 06:04 UTC
### Describe the bug

I'm experiencing an issue when running the run.py script in the SWE-agent project. I'm using a Windows environment with Python version 3.8.5.

### Steps/commands/code to Reproduce

Steps I've taken:

Checked dependencies and ensured that all required packages are properly installed.
Imported the necessary modules and verified the settings of the args argument.
Confirmed that the project structure hasn't undergone significant changes.
Ran the script in a clean virtual environment.
However, I keep encountering the following error message when running the run.py script:

Traceback (most recent call last):
  File "D:\AI\SWE-agent\run.py", line 321, in <module>
    main(args)
  File "D:\AI\SWE-agent\run.py", line 92, in main
    env = SWEEnv(args.environment)
  ...
  File "D:\AI\SWE-agent\sweagent\environment\utils.py", line 141, in __enter__
    signal.signal(signal.SIGALRM, self.handle_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'. Did you mean: 'SIGABRT'?

### Error message/results

Traceback (most recent call last):
  File "D:\AI\SWE-agent\run.py", line 321, in <module>
    main(args)
  File "D:\AI\SWE-agent\run.py", line 92, in main
    env = SWEEnv(args.environment)
  ...
  File "D:\AI\SWE-agent\sweagent\environment\utils.py", line 141, in __enter__
    signal.signal(signal.SIGALRM, self.handle_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'. Did you mean: 'SIGABRT'?

### System Information

I have examined this error message and attempted several troubleshooting steps, but haven't been successful in resolving the issue.

I kindly request your assistance in resolving this problem. Thank you very much for your help.

Feel free to customize the above description by including relevant details about the issue you're facing. Make sure to provide enough information so that the developers can understand the problem thoroughly and provide an appropriate solution.

### Checklist

- [X] I have copied the full command/code that I ran
- [X] I have copied the **full** log file/error message that was the result (if applicable)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code))

**Comment by klieret** [comment] 2024-04-09 13:52
Duplicate of #40, will be fixed with #17.

**Closed by klieret** 2024-04-09 13:52 UTC
Labels: bug
