### ISSUE TITLE
Express Setup + Run on windows

### ISSUE THREAD

**Issue by RudolphSikorskiy** [princeton-nlp/SWE-agent#116] opened 2024-04-06 19:56 UTC
### Describe the bug

Run command from readme "🏎️ Express Setup + Run" return error on windows 11 
```bash
exec /usr/local/bin/python: exec format error
```

### Steps/Code to Reproduce

Pull
```bash
(swe-agent) PS C:\REP\SWE-agent> docker pull --platform=linux/arm64 sweagent/swe-agent-run:latest
latest: Pulling from sweagent/swe-agent-run
6ee0baa58a3d: Pull complete
992a857ef575: Pull complete
3861a6536e4e: Pull complete
e5e6faea05ea: Pull complete
91c9495e7b5a: Pull complete
9da2a388277a: Pull complete
308655dc4d72: Pull complete
044e84ab5cad: Pull complete
d2f0448eacb4: Pull complete
fefa5ed070ca: Pull complete
be6ee2628ff4: Pull complete
a8702bbfe4b5: Pull complete
Digest: sha256:7159e9028e92856d7a72cd63b4b1f61e9bba81f104687dba9fb9a23db4084ebe
Status: Downloaded newer image for sweagent/swe-agent-run:latest
docker.io/sweagent/swe-agent-run:latest
```
Run
```bash
(swe-agent) PS C:\REP\SWE-agent> docker run --rm -it -v //var/run/docker.sock:/var/run/docker.sock 
    -e GITHUB_TOKEN="GITHUB_TOKEN" 
    -e OPENAI_API_KEY="OPENAI_API_KEY" --platform=linux/arm64 sweagent/swe-agent-run:latest 
    python run.py 
        --image_name=sweagent/swe-agent:latest 
        --model_name gpt4 
        --data_path https://github.com/modern-python/that-depends/issues/5 
        --config_file config/default_from_url.yaml  
        --skip_existing=False

exec /usr/local/bin/python: exec format error
```

### Expected Results

any result

### Actual Results

Do nothing with error 
output: 
```bash
exec /usr/local/bin/python: exec format error
```

### System Information

windows 11
swebench 1.0.1
sweagent/swe-agent-run   latest    5966b20a9632   3 hours ago   1.9GB

**Comment by klieret** [comment] 2024-04-07 01:00
Sorry, this is probably because we have mistakenly only provided docker containers for arm64. We hope to get this done today or early tomorrow. 

This is a duplicate of #107

**Closed by klieret** 2024-04-07 01:00 UTC
Labels: bug
